restructured the project (again)
to avoid the conflicts name produced when from the base.py import logical.py
and from logical.py import base.py, this produced a conflict name
ImportError: cannot import name base <- that was the error